/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 注册账号
         * @description 邮箱 + 密码注册,返回登录态与用户信息。注册开放度由 Supabase Auth 配置约束 (限公司邮箱域名 / 邀请制,见架构待确认项 1),服务端强制校验。
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 登录
         * @description 邮箱 + 密码登录,签发 session。登录入口按 IP/账号限失败次数(CLAUDE.md 安全 P0)。
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-bases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 列出全部知识库
         * @description 知识库全员平权,返回全量,不拼 user 过滤(CLAUDE.md 数据边界)。
         */
        get: operations["listKnowledgeBases"];
        put?: never;
        /** 创建知识库 */
        post: operations["createKnowledgeBase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-bases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 删除知识库
         * @description 级联删除库内 documents 与 doc_chunks(ON DELETE CASCADE)。前端二次确认不构成后端防护。
         */
        delete: operations["deleteKnowledgeBase"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-bases/{id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出库内文档及状态 */
        get: operations["listDocuments"];
        put?: never;
        /**
         * 上传文档(全异步入库)
         * @description 上传立即返回 { documentId, status: "pending" },解析/embedding/写库丢后台。 文件字节暂存服务端本地临时目录,pg-boss 载荷只带文件路径引用。
         */
        post: operations["uploadDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 轮询单份文档状态 */
        get: operations["getDocument"];
        put?: never;
        post?: never;
        /** 删除文档及其 chunk */
        delete: operations["deleteDocument"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * SSE 流式问答
         * @description RAG 流式问答:取会话上下文 → query rewriting → 向量检索 → LLM 流式生成。 响应为 text/event-stream。首字节(HTTP 200)发出后的错误只能走 event: error 在流内传递,不依赖 HTTP 状态码。前端 AbortController.abort() 透传取消上游 LLM fetch。
         *
         *     SSE 事件序列:先 meta(grounded 命中状态)→ 多个 token(逐字追加)→ done(收束,回传 conversationId); 流内异常走 error。每个事件按 `event:` 分派,`data:` 为对应 JSON。
         */
        post: operations["chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 列出当前用户的会话
         * @description 数据访问层强制注入 WHERE user_id = :currentUser。大数据量走游标分页。
         */
        get: operations["listConversations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查会话内消息
         * @description 必须校验 :id 归属当前用户(防 IDOR)。
         */
        get: operations["listConversationMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 全局只读查看所有用户的问答记录
         * @description 管理员审计路径,刻意不拼 user_id 过滤,校验 role === 'admin' (不得用 role !== 'user' 反向逻辑)。此调用是全系统唯一必须审计到人的操作, 服务端必带 admin_user_id + target_user_id 落审计。
         */
        get: operations["listAdminConversations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 全系统统一错误响应。绝不含 password_hash、密钥或 messages.content。 */
        ApiError: {
            error: {
                /**
                 * @description 机器可判读的错误码,如 LLM_TIMEOUT / UNAUTHORIZED / VALIDATION_ERROR。
                 * @example VALIDATION_ERROR
                 */
                code: string;
                /** @description 面向开发者的人类可读描述,不含敏感字段。 */
                message: string;
                /** @description 可选的结构化补充(如逐字段校验错误)。 */
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        /**
         * @description 用户角色。admin 唯一特权是只读 /api/admin/*。
         * @enum {string}
         */
        Role: "user" | "admin";
        /**
         * @description 文档全异步入库状态机,前端轮询此字段。
         * @enum {string}
         */
        DocumentStatus: "pending" | "processing" | "ready" | "failed";
        /**
         * @description 入库失败原因。scanned_no_text=扫描件拦截(产品边界内正常拒绝); parse_error=解析失败(真异常);unsupported_format=格式不支持。
         * @enum {string}
         */
        IngestFailReason: "scanned_no_text" | "parse_error" | "unsupported_format";
        /**
         * @description 支持的文档格式(pdf-parse / mammoth / fs)。
         * @enum {string}
         */
        DocumentFileType: "pdf" | "docx" | "txt";
        /** @enum {string} */
        MessageRole: "user" | "assistant";
        AuthCredentials: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        AuthResult: {
            user: components["schemas"]["User"];
            /** @description 兼容字段。Supabase Auth 下登录态走 session cookie,token 可能缺省; 保留以兼容架构文档 API 表中的 { token } 契约。 */
            token?: string;
        };
        /** @description 用户账号。password_hash 绝不出现在任何响应中。 */
        User: {
            id: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            /** Format: date-time */
            createdAt: string;
        };
        /** @description 知识库,全员共享,无 owner 字段。 */
        KnowledgeBase: {
            id: string;
            name: string;
            /** Format: date-time */
            createdAt: string;
        };
        CreateKnowledgeBaseRequest: {
            name: string;
        };
        /** @description 删除结果与级联影响量(供审计记录)。 */
        DeleteKnowledgeBaseResult: {
            id: string;
            deletedDocuments: number;
            deletedChunks: number;
        };
        /** @description 文档元数据。失败时带 errorReason,不入库空内容。 */
        DocumentMeta: {
            id: string;
            knowledgeBaseId: string;
            fileName: string;
            fileType: components["schemas"]["DocumentFileType"];
            status: components["schemas"]["DocumentStatus"];
            errorReason?: components["schemas"]["IngestFailReason"];
            /** Format: date-time */
            createdAt: string;
        };
        UploadDocumentRequest: {
            /**
             * Format: binary
             * @description 文档文件(pdf/docx/txt)。
             */
            file: string;
        };
        /** @description 上传即时返回,后台异步入库。 */
        UploadDocumentResult: {
            documentId: string;
            /**
             * @description 上传即返回,固定为 pending。
             * @constant
             */
            status: "pending";
        };
        Conversation: {
            id: string;
            userId: string;
            title: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description 一条问答记录。grounded 标记回答当时是否有文档依据;残答不落此表。 */
        Message: {
            id: string;
            conversationId: string;
            role: components["schemas"]["MessageRole"];
            content: string;
            sequenceNumber: number;
            /** @description 该 assistant 回答是否命中文档依据;user 消息通常缺省。 */
            grounded?: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        ConversationPage: {
            items: components["schemas"]["Conversation"][];
            /** @description 下一页游标;为 null 表示已到末页。 */
            nextCursor: string | null;
        };
        MessagePage: {
            items: components["schemas"]["Message"][];
            /** @description 下一页游标;为 null 表示已到末页。 */
            nextCursor: string | null;
        };
        /** @description sessionId 是易失的上下文键(刷新即换),conversationId 是持久历史键。 首次带某 sessionId 请求时后端新建 conversation,并在 done 事件回传其 conversationId。 */
        ChatRequest: {
            /** @description 检索只在此单库内,不跨库。 */
            knowledgeBaseId: string;
            /** @description 前端生成,标识一次浏览器会话;必须归属当前 user_id。 */
            sessionId: string;
            question: string;
            /** @description 可选;前端从上一轮 done 拿到后回传以显式复用会话。 */
            conversationId?: string;
        };
        /**
         * @description SSE 事件类型,前端按 `event:` 分派。
         * @enum {string}
         */
        SseEventType: "meta" | "token" | "error" | "done";
        /** @description 首个事件,携带 grounded 命中状态与最高相似度。 */
        SseMetaEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "meta";
            /** @description false 表示最高相似度低于阈值,回答属常识推测(需求功能 3)。 */
            grounded: boolean;
            topSimilarity: number;
        };
        /** @description 逐字追加的回答内容。 */
        SseTokenEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "token";
            delta: string;
        };
        /** @description 首字节发出后的流内错误,前端在已渲染内容后追加提示。 */
        SseErrorEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error";
            message: string;
        };
        /** @description 正常收束,回传持久化的 conversationId。 */
        SseDoneEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "done";
            conversationId: string;
        };
        /** @description 单个 SSE 事件的 data JSON,按 type 判别。 */
        SseEvent: components["schemas"]["SseMetaEvent"] | components["schemas"]["SseTokenEvent"] | components["schemas"]["SseErrorEvent"] | components["schemas"]["SseDoneEvent"];
    };
    responses: {
        /** @description 请求参数不合法 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description 未登录或登录态失效 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description 已登录但无权访问(如非 admin 访问 /api/admin/*) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description 资源不存在 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description 触发限流(认证入口按 IP/账号限失败次数) */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        /** @description 资源 ID(bigserial 序列化为字符串,避免 JS number 精度丢失)。 */
        IdPath: string;
        /** @description 游标分页锚点,取上一页 nextCursor;首页省略。 */
        CursorQuery: string;
        /** @description 单页条数。 */
        LimitQuery: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthCredentials"];
            };
        };
        responses: {
            /** @description 注册成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description 邮箱已被注册 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthCredentials"];
            };
        };
        responses: {
            /** @description 登录成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    listKnowledgeBases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 知识库列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBase"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createKnowledgeBase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateKnowledgeBaseRequest"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBase"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteKnowledgeBase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 资源 ID(bigserial 序列化为字符串,避免 JS number 精度丢失)。 */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功,返回级联影响量(供审计) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteKnowledgeBaseResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 资源 ID(bigserial 序列化为字符串,避免 JS number 精度丢失)。 */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 文档列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentMeta"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    uploadDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 资源 ID(bigserial 序列化为字符串,避免 JS number 精度丢失)。 */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["UploadDocumentRequest"];
            };
        };
        responses: {
            /** @description 已接收,后台入库中 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadDocumentResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description 不支持的文件格式(仅 pdf/docx/txt) */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 资源 ID(bigserial 序列化为字符串,避免 JS number 精度丢失)。 */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 文档状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentMeta"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 资源 ID(bigserial 序列化为字符串,避免 JS number 精度丢失)。 */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功,无响应体 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    chat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description SSE 事件流。以下 schema 描述单个 SSE 事件的 data JSON。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEvent"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description sessionId 不归属当前 user_id(禁止读他人上下文) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listConversations: {
        parameters: {
            query?: {
                /** @description 游标分页锚点,取上一页 nextCursor;首页省略。 */
                cursor?: components["parameters"]["CursorQuery"];
                /** @description 单页条数。 */
                limit?: components["parameters"]["LimitQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 会话分页列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listConversationMessages: {
        parameters: {
            query?: {
                /** @description 游标分页锚点,取上一页 nextCursor;首页省略。 */
                cursor?: components["parameters"]["CursorQuery"];
                /** @description 单页条数。 */
                limit?: components["parameters"]["LimitQuery"];
            };
            header?: never;
            path: {
                /** @description 资源 ID(bigserial 序列化为字符串,避免 JS number 精度丢失)。 */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 消息分页列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description 会话不归属当前用户 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listAdminConversations: {
        parameters: {
            query?: {
                /** @description 可选,按目标用户过滤;缺省时返回全体。 */
                targetUserId?: string;
                /** @description 游标分页锚点,取上一页 nextCursor;首页省略。 */
                cursor?: components["parameters"]["CursorQuery"];
                /** @description 单页条数。 */
                limit?: components["parameters"]["LimitQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 全局会话分页列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
}
